###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = kitty -e yazi
$menu = rofi -show drun
$chrome = google-chrome-stable
$browser = qutebrowser
$waybar = pkill waybar || waybar
$dbAnalyzer = dbeaver
$requester = postman
$musicPlayer = spotify
$discord = vesktop
