###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun
$browser = google-chrome-stable
$waybar = pkill waybar || waybar
$dbAnalyzer = beekeeper-studio
$requester = yaak-app
$musicPlayer = spotify
